# Generated by Django 4.1.3 on 2022-11-08 20:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_comments_approved_comment_comments_create_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 8, 20, 5, 41, 440449, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 8, 20, 5, 41, 440449, tzinfo=datetime.timezone.utc)),
        ),
    ]
