# Generated by Django 4.1.3 on 2022-11-20 16:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_comments_create_date_alter_post_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 20, 16, 50, 58, 689025, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 20, 16, 50, 58, 689025, tzinfo=datetime.timezone.utc)),
        ),
    ]
